### ISSUE TITLE
zeo++/voro++ code vendoring

### ISSUE THREAD

**Issue by ltalirz** [chr1shr/voro#12]
from https://github.com/chr1shr/voro/issues/8#issuecomment-826656148

> About the `zeo/` subfolder in voro++: is that the predecessor to zeo++ ? Is this folder still maintained?
> I'm asking this because also zeo++ ["vendors" voro++](https://github.com/mharanczyk/zeoplusplus) (i.e. ships a copy of it) and it might be useful to disentangle the two repositories so that new features and bug fixes made in one place always propagate to the other (and vice versa).

**Comment by chr1shr** [comment]
This is a good point. Currently the zeo++ directory contains some of the test codes that I used for Zeo++ integration. It is not a full version of Zeo++ and never was. But it would indeed be good to separate these two repositories.

My student and I are getting ready to release a new version of Voro++, and I should speak to @mharanczyk about this.
